// <auto-generated />
using EntityFrameworkWithSqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EntityFrameworkWithSqlite.Migrations
{
    [DbContext(typeof(BookContext))]
    partial class BookContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("EntityFrameworkWithSqlite.Entity.Binnacle", b =>
                {
                    b.Property<int>("BinnacleId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BinnacleTitle");

                    b.HasKey("BinnacleId");

                    b.ToTable("Binnacles");
                });
#pragma warning restore 612, 618
        }
    }
}
